server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      INDENT_OUTPUT: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: user-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
jwt:
  secret: ${JWT.SECRET}
  issuer: ${JWT.ISSUER}
  duration_second: ${JWT.DURATION_TIME}
