server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:user;MODE=MYSQL;DB_CLOSE_DELAY=-1

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      INDENT_OUTPUT: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: grade-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
jwt:
  secret: ${JWT.SECRET}
  issuer: ${JWT.ISSUER}
  duration_second: ${JWT.DURATION_TIME}
